### ISSUE TITLE
[bsmrkds-02] - Create Stack Data Structure

### ISSUE THREAD

**Issue by Oscarz90** [Oscarz90/bismarck-cs#21]
# 🚀 Feature request

## :pencil: Description
Create the Stack data structure, It should include the follow methods and attributes:

Methods:
Push: O(1)
Pop: O(1)
Search: O(n)
IsEmpty: O(1)

Attributes:
Size: Length of stack

Note: A required time complexity is given for all the methods

## :bulb: Describe the solution you'd like
Creating a class with the methods describe above.

## :pushpin: Describe alternatives you've considered (:see_no_evil: optional)
N/A

## :wrench: Additional context (:see_no_evil: optional)
N/A

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue
